### ISSUE TITLE
Could not find love executable in AppDir. The AppImage has an unknown format.

### ISSUE THREAD

**Issue by pakeke-constructor** [pfirsich/makelove#38]
Hi,
I'm trying to build with the classic AppImage setup.
However, the appImage is not built, and instead whilst extracting, love's nogame screen shows up.

I'd like to clarify:
The build process *does not succeed.*
Although the `.love` file is built correctly, the issue is to do with the extraction of the AppImage.

## Output:
```
$ makelove appimage

Loading config from default path 'makelove.toml'
Found conf.lua
Assuming default löve version '11.3'
Building targets: appimage
Assembling game directory..
Created makelove-build/love/UMG.love
>> Building target appimage
Downloading https://github.com/pfirsich/love-appimages/releases/download/v3/love-11.3-x86_64.AppImage..
Extracting source AppImage '/tmp/tmpcb2fk_yw.AppImage'..
Could not find love executable in AppDir. The AppImage has an unknown format.
```

## OS and PC specs:
```
Linux Mint 21.1 Cinnamon
Cinnamon version: 5.6.8
Processor:  i7-12700
Memory: 32gb
```

I have tried with other AppImages, including 11.4 and 12.0 AppImages.
The same error occurs.

Any help would be greatly appreciated!
Thanks for the amazing effort in making / maintaining this software. :)

**Comment by pakeke-constructor** [comment]
I'm wondering if it's potentially to do with the university machine I'm using?

The machine I am on does not have full access to root, so there could be issues in that regard.
I'll try get access to another machine and keep you updated.

**Comment by pakeke-constructor** [comment]
Hello- I have got it working by just using my own machine with WSL, after installing FUSE

I honestly have no idea why the original way wasn't working.
Likely to do with my university computer set-up, since they put a few restrictions in

**Comment by pfirsich** [comment]
I think that error message is probably not great and I would like to know what is going on there.

Could you please try it out again and then try to run the downloaded AppImage (in the /tmp directory) manually with `--appimage-extract`? Because that is what makelove is doing as well. It might be that this silently fails i.e. the command does not actually fail, but it also doesn't extract itself properly.
If it does extract properly (there should be a squashfs-root directory afterwards), could you add `tree` or `find` output of that directory?

If that does indeed misbehave, could you check the permissions of the file (with `stat` or `ls -l`)?

**Comment by pakeke-constructor** [comment]
Sure, I'll have a poke around this afternoon and keep this thread updated.
