### ISSUE TITLE
Issue building with custom `source_appimage`

### ISSUE THREAD

**Issue by pakeke-constructor** [pfirsich/makelove#39]
Hello, I am having an issue when attempting to build with a custom `source_appimage`.

The custom AppImage definitely exists, but is not being picked up by `subprocess.run` for some reason.

## Repro:
```
$ ls build/love/linux64
love.AppImage

$
$ makelove appimage
Loading config from default path 'makelove.toml'
Found conf.lua
Assuming default löve version '11.3'
Building targets: appimage
Assembling game directory..
Created build_output/love/umg.love
>> Building target appimage
Extracting source AppImage 'build/love/linux64/love.AppImage'..
Traceback (most recent call last):
  File "/home/unix43/.local/bin/makelove", line 8, in <module>
    sys.exit(main())
  File "/home/unix43/.local/lib/python3.10/site-packages/makelove/makelove.py", line 349, in main
    build_linux(config, version, target, target_directory, love_file_path)
  File "/home/unix43/.local/lib/python3.10/site-packages/makelove/linux.py", line 134, in build_linux
    ret = subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'build/love/linux64/love.AppImage'
```

## makelove.toml:
```toml
name = "umg"

love_files = [
    "::git-ls-tree::",
    "-*/*.md", # no markdown files
    "-*/.*", # .git, .github
]

default_targets = ["appimage"]

# By default this is "makelove-build"
build_directory = "build_output"

[appimage]
# custom appimage:
source_appimage = "build/love/linux64/love.AppImage"

```

**Comment by pfirsich** [comment]
I can reproduce this issue, so this is very likely a bug. I will look into it this evening!

**Comment by pfirsich** [comment]
I see what the issue is. The AppImage always extracts itself to the current working directory, so I cannot easily control where I run it from – it has to be the directory I want to extract it *to*. 
This means that the path in `source_appimage` would have to be relative to the target's directory (e.g. `build_output/appimage` in your case), but that is not an option, because that directory is cleared before the target is built. 

The alternative is to specify `source_appimage` as an **absolute path**.
I added a fix that will make the path absolute if it is not already given as an absolute path.
If you only want to official released versions, you can just make the path absolute as a workaround.

**Comment by pakeke-constructor** [comment]
Thank you very much!
